export const GET_INHABITANTS_LIST = "GET_INHABITANTS_LIST";
export const SET_CHECKED = "SET_CHECKED";
export const SET_PAGINATION_SIZE = "SET_PAGINATION_SIZE";
export const GET_PROFESSION_LIST = "GET_PROFESSION_LIST";
